### ISSUE TITLE
Integration-Tests is running before Application is running

### ISSUE THREAD

**Issue by hupling** [bszeti/kubernetes-integration-test#1]
How do you know that the Mock-Server and Application has started before the integration-test is running?
https://github.com/bszeti/kubernetes-integration-test/blob/e23a921742bcb67fc5e4feb76c980116883be51f/Jenkinsfile-declarative#L146

**Comment by bszeti** [comment]
As I remember Jenkins waits for all the containers to reach the ready state before executing the stages. So it's important to have proper readinessProbe for each to avoid an early test execution.

**Comment by hupling** [comment]
![grafik](https://user-images.githubusercontent.com/11695964/70302597-c8211f00-17fd-11ea-99cd-9885e8b3f791.png) 
After about 100 secondes unhealthy state the pod will be killed. A new pod will be created and starts. The problem is that my application needs more than 100 seconds to start. The config for the readiness probe settings is 60 *10 =600 seconds.

**Comment by bszeti** [comment]
Pods are restarted because of the "livenessProbe" not the "readinessProbe". If livenessProbe is not set for any of the containers, then they are restarted because of another reason. Maybe the memory limits are reached, because -Xmx was not set for a java process?
Just right after the Pod is killed, the status may indicate why it was stopped.

**Comment by hupling** [comment]
Thank you very much. I think that I need to put the [slaveConnectTimeout](https://github.com/jenkinsci/kubernetes-plugin#specifying-a-different-default-agent-connection-timeout) higher. I didn't know that you can add the parameter easily. 
![grafik](https://user-images.githubusercontent.com/11695964/70436208-0a11c580-1a89-11ea-9f87-bb59819a0335.png)
